name: Deploy Infrastructure

on:
  workflow_run:
    workflows: ["Build and Push Docker Image"] # <- nombre definido en build-and-push.yml
    types:
      - completed

jobs:
  terraform:
    runs-on: ubuntu-latest
    needs: []

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Recuperar el artifact exportado en build-and-push.yml
      - name: Download image URI artifact
        uses: actions/download-artifact@v3
        with:
          name: image-uri

      - name: Read image URI
        id: image
        run: |
          IMAGE_URI=$(cat image-uri.txt)
          echo "image_uri=$IMAGE_URI" >> $GITHUB_OUTPUT

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Terraform Plan
        working-directory: terraform
        run: terraform plan -out=tfplan -var="docker_image_uri=${{ steps.image.outputs.image_uri }}"

      - name: Terraform Apply
        working-directory: terraform
        run: terraform apply -auto-approve tfplan
